### ISSUE TITLE
Displays

### ISSUE THREAD

**Issue by finnie2006** [enjoyneering/MatrixClock#2]
Hello, currently this project is made for 5 segments off the max 7219, i have 8, can you make an option in the settings to set the amount off displays? i cant do it as you only share compiled bins

**Comment by enjoyneering** [comment]
Unfortunately no. Sorry.

**Comment by finnie2006** [comment]
Why not, I myself built a matrix with 8 displays, you can do many more things with 8 displays, for example display the seconds, it seemed like a good project, but then I will have to use another repo anyway... pity

**Comment by finnie2006** [comment]
> Unfortunately no. Sorry.

Whats the reason for that?

**Comment by finnie2006** [comment]
??
